name: daily github-trending
on:
  schedule:
    - cron: "0 2 * * *" 

jobs:
  github-trending:
    name: daily github-trending
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
            python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cssselect lxml pyquery requests schedule
    - name: Run Scraper
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scraper.py
    # Runs a set of commands using the runners shell
    - name: push to origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        echo start push
        git config --global user.name "araguaci"
        git config --global user.email "araguaci@gmail.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
